### ISSUE TITLE
make the bot add a reaction to mail once its been responded to

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/arcadia_automation_bot#33]
would prevent double ups on sending mail, and also tell us what still needs responding to

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/879196662491394128)

**Comment by SanctusAnimus** [comment]
Implemented in e057c7b
